### ISSUE TITLE
Poor HD Celeb cropping

### ISSUE THREAD

**Issue by abi98213** [LynnHo/HD-CelebA-Cropper#2]
I am using your code, I have done each step as specified but images produced are just stretched and noisy.
![000322](https://user-images.githubusercontent.com/32646935/48661052-f9616c80-ea8d-11e8-8a4a-b93734d67834.png)

**Comment by LynnHo** [comment]
@mabdullahrafique  What command did you use?

**Comment by xyzdcgan** [comment]
Hello can you help me with the dataset when i go to dataset link there i  download img_celeba.7z it download files but which are not jpg files so from where we can download the images. there are 3 folder img_align_celeba.zip which are jpg files but with 178-218 resolution. so where are the high resolution image...??

**Comment by munkim** [comment]
What exactly is this stretch mark?

**Comment by ZYzhouya** [comment]
I meet the same issue that **the face don't located in the image center.** 
I use the command "python align_kwai.py --img_dir ./ -crop_size_h 512 --crop_size_w 512 --order 4 --save_format jpg --n_worker 32"

@LynnHo

**Comment by LynnHo** [comment]
@ZYzhouya did you totally follow the README steps?
