### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by xyzdcgan** [LynnHo/HD-CelebA-Cropper#3]
Hello can you help me with the dataset when i go to dataset link there i download img_celeba.7z it download files but which are not jpg  files and there are files like img_celeba.7z.001 so from where we can download the images. there are 3 folder img_align_celeba.zip which are jpg files but with 178-218 resolution. so where are the high resolution image...??

**Comment by LynnHo** [comment]
@xyzdcgan Download files in this folder and unzip the files.
![image](https://user-images.githubusercontent.com/16457298/50970833-7accfc80-151d-11e9-9449-c684d697ccf2.png)

**Comment by xyzdcgan** [comment]
@LynnHo  Okay, from that 3 are getting download, i am using drive link, so once it complete zipping that it start download of 3 files which are and also extracted those and got these result like: 
![dwnload](https://user-images.githubusercontent.com/44637302/50973960-2c653100-1510-11e9-9fbe-345ad36caa18.png)

**Comment by LynnHo** [comment]
@xyzdcgan 
![image](https://user-images.githubusercontent.com/16457298/50974254-c7b4d100-1525-11e9-8ecc-c403ed6d9fc0.png)
There should be 14 files like above, you can use `7z x img_celeba.7z.001` to extract them.

**Comment by xyzdcgan** [comment]
@LynnHo  That gives Error : E_FAIL 
7z x img_celeba.7z.001 

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_IN,Utf16=on,HugeFiles=on,4 CPUs)

Processing archive: img_celeba.7z.001

Error: E_FAIL                


Trying to solve this if you can have any solution for this it would be great

 I have plenty of space so why does,

Do i need to download all 14 parts

**Comment by LynnHo** [comment]
@xyzdcgan Yes, you need all 14 parts.

**Comment by xyzdcgan** [comment]
@LynnHo  Okay 

> @xyzdcgan Yes, you need all 14 parts.

Okay

**Comment by xyzdcgan** [comment]
@LynnHo  Also i am trying to convert the checkpoint files to .pb which is done through tensorflow frozen_graph.py in which i pass Adam And adam_1 as the output nodes and which is generated but when i try it out it gives and error of adam not convert with float32 to float32_ref. can you tell if you have used any other optimizer to train the model as it only accept adam as output node. not relu or other

**Comment by LynnHo** [comment]
@xyzdcgan I am sorry that I haven't got the experience on this problem.

> @LynnHo Also i am trying to convert the checkpoint files to .pb which is done through tensorflow frozen_graph.py in which i pass Adam And adam_1 as the output nodes and which is generated but when i try it out it gives and error of adam not convert with float32 to float32_ref. can you tell if you have used any other optimizer to train the model as it only accept adam as output node. not relu or other

**Comment by xyzdcgan** [comment]
@LynnHo  Have you ever converted your ckpt files to .pb extension file format.

**Comment by LynnHo** [comment]
@xyzdcgan No, I haven't.

**Comment by xyzdcgan** [comment]
@LynnHo 

 python3 hd_celeba.py --data_dir ./data --crop_size 512 --order 4 --save_format jpg --n_worker 32
Use OpenCV
  0%|                                                                                                                                         | 0/202599 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "hd_celeba.py", line 105, in work
    mode=args.mode)
  File "/home/ios/hdimage/HD-CelebA-Cropper-master/cropper.py", line 64, in align_crop_5pts_opencv
    move = np.array([img.shape[1] // 2, img.shape[0] // 2])
AttributeError: 'NoneType' object has no attribute 'shape'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hd_celeba.py", line 109, in <module>
    for _ in tqdm(pool.imap(work, range(len(img_names))), total=len(img_names)):
  File "/home/ios/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 999, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by LynnHo** [comment]
@xyzdcgan Did you follow the readme step by step? It seems to be the problem of image loading, how did you organize the files?

**Comment by LynnHo** [comment]
@xyzdcgan try python3 hd_celeba.py --data_dir . --crop_size 512 --order 4 --save_format jpg --n_worker 32

**Comment by xyzdcgan** [comment]
@LynnHo  I am following the exact structure as mention in readme 
![screenshot from 2019-01-11 15-27-45](https://user-images.githubusercontent.com/44637302/51026894-9257c400-15b5-11e9-8e99-9f42d45f91f2.png)

**Comment by xyzdcgan** [comment]
> @xyzdcgan try python3 hd_celeba.py --data_dir . --crop_size 512 --order 4 --save_format jpg --n_worker 32

Working now Thanks

**Comment by copperwiring** [comment]
@xyzdcgan Were you able to get the data (.7z files) from the 'images' directory in CelebA? To me it doens't work and throws `cannot open the file as archive` error 

![image](https://user-images.githubusercontent.com/23316280/118344883-b27d5200-b4e5-11eb-8bf4-a31e039f1f39.png)
