### ISSUE TITLE
why i got only one image？

### ISSUE THREAD

**Issue by thinkerthinker** [LynnHo/HD-CelebA-Cropper#4]
I have tried all commands as you showed in readme.md.  Whether I use opencv or skicit, I can only get one image result, all other images fail. I only got 179034.jpg. I followed readme.md step by step, I don't know where it is wrong...... Can you help me?

**Comment by LynnHo** [comment]
@thinkerthinker You close the issue, have you solved the problem?

**Comment by thinkerthinker** [comment]
@LynnHo Yes, thanks.
