### ISSUE TITLE
Celeb dataset

### ISSUE THREAD

**Issue by shbnm21** [LynnHo/HD-CelebA-Cropper#5]
Hello 
I tried to download the celeb dataset from the link u provided .I tried to manually unzip the img_celeba.7z but no luck.file is currupted.
I tried to open it with 7z tool but again getting message can't open archive.

So can u provide in any other way to download celeb data.

**Comment by LynnHo** [comment]
@shbnm21 I am sorry I do not know other ways to access the dataset other than the links in README.md.

**Comment by shbnm21** [comment]
Ok no problem.
If I use my own dataset what changes do I need to do?
That _DEFAULT_MEAN_LANDMARKS array remains same or need to change that.

**Comment by LynnHo** [comment]
@shbnm21 Organize your dataset as below,
```
path_to_dataset
├── data/*.jpg
└── list_landmarks_celeba.txt
```
and you should provide the landmarks of images with the same format as `list_landmarks_celeba.txt` of CelebA.

**Comment by shbnm21** [comment]
Ok,thanks a ton..

**Comment by shbnm21** [comment]
There are various Android apps to crop the images.

And there are various tools to deploy python code on Android device.

My question is if I deploy this on Android 

How to directly take images either from gallery or camera and crop them ?

**Comment by LynnHo** [comment]
@shbnm21 I am sorry I cannot help since I have no experience on Android.

**Comment by shbnm21** [comment]
Ok
