### ISSUE TITLE
Can I use it for other datasets?

### ISSUE THREAD

**Issue by ilovecv** [LynnHo/HD-CelebA-Cropper#8]
Hi,

Thank you very much for sharing a useful tool. I am wondering if I can use it for other face datasets?
How to set the move_h, move_w parameters?

Thanks!

**Comment by LynnHo** [comment]
@ilovecv Yes, you can use the code for any dataset if you provide the landmarks. Like here https://github.com/LynnHo/Facial-Landmarks-of-Face-Datasets. Default `move_h` and `move_w` will be fine, they are used for tuning the location of the face in the image.

**Comment by ilovecv** [comment]
Hi @LynnHo,
Thank you very much for your quick reply. I used the command: python align.py --crop_size_h 256 --crop_size_w 256 --order 4 --save_format jpg --n_worker 32 to align the dataset. However, the result looks not correct:
original image:
![1](https://user-images.githubusercontent.com/11083384/72009882-9ab7fe80-320b-11ea-88b9-b82ae8ec693a.jpg)
aligned image:
![10](https://user-images.githubusercontent.com/11083384/72010045-fd10ff00-320b-11ea-8302-221f8990824a.jpg)

May I ask the reasons? Thanks!

**Comment by LynnHo** [comment]
@ilovecv Which dataset did you use?  Have you provided the correct landmark format?
